# Generated by Django 5.1.5 on 2025-02-18 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='studymaterial',
            name='material_type',
        ),
        migrations.RemoveField(
            model_name='studymaterial',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='profile_documents/'),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='file',
            field=models.FileField(upload_to='study_materials/'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
