# Generated by Django 5.1.5 on 2025-02-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_remove_schedule_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
