# Generated by Django 5.1.5 on 2025-02-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_facultyprofile_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='facultyprofile',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='faculty_documents/'),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='faculty_photos/'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
