# Generated by Django 5.1.5 on 2025-02-19 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_rename_date_schedule_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
