# Generated by Django 5.1.5 on 2025-02-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0007_reschedulerequest_delete_studymaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
