# Generated by Django 5.1.5 on 2025-02-23 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0008_schedule_confirmed_at_schedule_is_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='start_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='end_date',
        ),
    ]
