# Generated by Django 5.1.5 on 2025-02-23 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0009_rename_start_date_schedule_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reschedulerequest',
            old_name='new_end_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='reschedulerequest',
            name='new_start_date',
        ),
    ]
